config/routes.rb
Rails.application.routes.draw do
  # get '/students', to: 'students#index', as: 'students'
  # get '/students/new', to: 'students#new', as: 'new_student'
  # post '/students', to: 'students#create'
  # get '/developers', to: 'students#index', as: 'students'
  resources :students, except: [ :destroy ]
  resources :wolves
  # resources :dogs, only: [:index, :new, :create]
  root('students#index')

  get '/login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create', as: 'sessions'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :enrollments
  has_many :students, through: :enrollments
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :course
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
  INVALID_NAMES = ['dog', 'Dog']
  
  validates :name, :email, presence: true
  validates :name, exclusion: {in: INVALID_NAMES }
  validate :is_eighteen?

  has_many :courses
  has_many :students, through: :enrollments

  # make sure that the DOB is at least 18 years ago...
  # make sure that the student's name is not "dog"

  private

  def is_eighteen?
    if self.dob && self.dob >= (Date.today - 18.years)
      errors.add(:dob, "must be over eighteen years ago")
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  private

  def current_user
    @current_user = User.find_by(id: session[:user_id])
  end

  def authorize_user
    if !logged_in?
      flash[:notice] = 'You are not allowed to do that unless you are logged in'
      redirect_to login_path
    end
  end

  def logged_in?
    !!session[:user_id]
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params['username'])
    if user.present?
      session[:user_id] = user.id
      redirect_to students_path
    else
      flash[:notice] = "The username you provided did not match our records. Please double check and try again."
      redirect_to login_path
    end
  end

  def destroy
    session.clear
    redirect_to login_path
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_action :authorize_user, only: [:new, :edit, :update, :create]

  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    # only allow logged in users to see this form
    @student = Student.new
  end

  def create
    @student = Student.new( student_params(:name, :email, :dob) )
    if @student.save
      redirect_to student_path(@student)
    else
      render :new
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    @student.update(student_params(:name, :email, :dob) )
    redirect_to @student
  end

  private

  def student_params(*args)
    params.require(:student).permit(*args)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # def make_link_to(body, path)
  #   "<a href='#{path}'>#{body}</a>".html_safe
  # end

  # def text_field_tag(field_name)
  #   "<input type='text' name='#{field_name.to_s}' id='#{field_name.to_s}'/>".html_safe
  # end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentLister</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul>
      <% if logged_in? %>
        <li>Welcome, <%= current_user.username %> </li>
        <li><%= link_to "Log Out", logout_path, method: 'DELETE' %> </li>
      <% else %>
        <li><%= link_to "Login", login_path %> </li>
      <% end %>
    </ul>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<% if student.errors.any? %>
  <ul>
    <% student.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for( student ) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name%>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :dob %>
  <%= f.date_field :dob %>
  <%= f.submit %>
<% end %>

app/views/students/edit.html.erb
<h1>Edit a Student</h1>

<%= render partial: 'form', locals: {student: @student} %>

app/views/students/index.html.erb
<h1>All Students</h1>

<ul>
  <% @students.each do |student| %>
    <li><%= link_to student.name, student %></li>
  <% end %>
</ul>

<% if logged_in? %>
  <%= link_to "Create a Student", new_student_path %>
<% end %>

app/views/students/new.html.erb
<h1>Create a Student</h1>

<%= render partial: 'form', locals: {student: @student} %>

<%= link_to "Back", students_path %>

app/views/students/show.html.erb
<h1><%= @student.name %></h1>
<p><%= @student.email %></p>

<%= session['user_id'] %>

<%= link_to "Back", students_path %>
<%= link_to "Edit", edit_student_path(@student) %>